### ISSUE TITLE
Maven Repository for Dependency Resolution

### ISSUE THREAD

**Issue by TheFlagCourier** [TheNewEconomy/TheNewChat#2]
I'm working on a draft of a pom.xml for Towny - I've noticed that TNC is not on the maven repository at dl.bintray.com. Wondering if it could be added, or if you had other plans.

**Comment by creatorfromhell** [comment]
Deployed TNC.

```
<dependency>
  <groupId>net.tnemc.tnc</groupId>
  <artifactId>TheNewChat</artifactId>
  <version>1.5.0.0</version>
</dependency>
```
